name: Scala CLA
on:
  pull_request:
    branches-ignore:
      - 'language-reference-stable'
  push:
    branches:
      - 'language-reference-stable'
  merge_group:
permissions:
  contents: write
  pull-requests: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: ./project/scripts/check-cla.sh
      if: github.event_name == 'pull_request'
      env:
        AUTHOR: ${{ github.event.pull_request.user.login }}
