name: scaladoc

on:
  push:
    branches-ignore:
      - 'language-reference-stable'
      - 'gh-readonly-queue/**'
  pull_request:
    branches-ignore:
      - 'language-reference-stable'
  merge_group:
permissions:
  contents: read

jobs:
  build:
    env:
      AZURE_STORAGE_SAS_TOKEN: ${{ secrets.AZURE_STORAGE_SAS_TOKEN }}
    runs-on: ubuntu-latest
    if: "github.event_name == 'merge_group'
         || (    github.event_name == 'pull_request'
           && !contains(github.event.pull_request.body, '[skip ci]')
           && !contains(github.event.pull_request.body, '[skip docs]')
         )
         || contains(github.event.ref, 'scaladoc')
         || contains(github.event.ref, 'main')"

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'sbt'

      - name: Compile and test scala3doc-js
        run: ./project/scripts/sbt scaladoc-js-main/test

      - name: Compile and test
        run: |
          ./project/scripts/sbt scaladoc/test
          ./project/scripts/cmdScaladocTests

      - name: Locally publish self
        run: ./project/scripts/sbt scaladoc/publishLocal

      - name: Generate self documentation
        run: ./project/scripts/sbt scaladoc/generateSelfDocumentation

      - name: Generate testcases documentation
        run: ./project/scripts/sbt scaladoc/generateTestcasesDocumentation

      - name: Generate reference documentation
        run: ./project/scripts/sbt scaladoc/generateReferenceDocumentation

      - name: Generate Scala 3 documentation
        run: ./project/scripts/sbt scaladoc/generateScalaDocumentation

      - name: Generate documentation for example project using dotty-sbt
        run: ./project/scripts/sbt "sbt-test/scripted sbt-dotty/scaladoc"

      - name: Generate index file
        run: scaladoc/scripts/mk-index.sh scaladoc/output > scaladoc/output/index.html

      - name: Upload documentation to server
        uses: azure/CLI@v1
        if: env.AZURE_STORAGE_SAS_TOKEN
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        with:
          inlineScript: |
            DOC_DEST=$(echo pr-${PR_NUMBER:-${GITHUB_REF##*/}} | tr -d -c "[-A-Za-z0-9]")
            echo uplading docs to https://scala3doc.virtuslab.com/$DOC_DEST
            az storage container create --name $DOC_DEST --account-name scala3docstorage --public-access container
            az storage blob upload-batch --overwrite true -s scaladoc/output -d $DOC_DEST --account-name scala3docstorage

  stdlib-sourcelinks-test:
    runs-on: ubuntu-latest
    # if false - disable flaky test
    if: "false && ((    github.event_name == 'pull_request'
           && !contains(github.event.pull_request.body, '[skip ci]')
           && !contains(github.event.pull_request.body, '[skip docs]')
         )
         || contains(github.event.ref, 'scaladoc')
         || contains(github.event.ref, 'scala3doc')
         || contains(github.event.ref, 'main'))"

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Test sourcelinks to stdlib
        run: true # ./project/scripts/sbt scaladoc/sourceLinksIntegrationTest:test
